onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix hexadecimal /registrosegmento/clock
add wave -noupdate -radix hexadecimal /registrosegmento/habilita
add wave -noupdate -radix hexadecimal /registrosegmento/entradaDados
add wave -noupdate -radix hexadecimal /registrosegmento/leitura_Escrita
add wave -noupdate -radix hexadecimal /registrosegmento/reset
add wave -noupdate -radix hexadecimal /registrosegmento/seletor
add wave -noupdate -radix hexadecimal /registrosegmento/soma_IP
add wave -noupdate -radix hexadecimal -childformat {{/registrosegmento/saidaDados(15) -radix hexadecimal} {/registrosegmento/saidaDados(14) -radix hexadecimal} {/registrosegmento/saidaDados(13) -radix hexadecimal} {/registrosegmento/saidaDados(12) -radix hexadecimal} {/registrosegmento/saidaDados(11) -radix hexadecimal} {/registrosegmento/saidaDados(10) -radix hexadecimal} {/registrosegmento/saidaDados(9) -radix hexadecimal} {/registrosegmento/saidaDados(8) -radix hexadecimal} {/registrosegmento/saidaDados(7) -radix hexadecimal} {/registrosegmento/saidaDados(6) -radix hexadecimal} {/registrosegmento/saidaDados(5) -radix hexadecimal} {/registrosegmento/saidaDados(4) -radix hexadecimal} {/registrosegmento/saidaDados(3) -radix hexadecimal} {/registrosegmento/saidaDados(2) -radix hexadecimal} {/registrosegmento/saidaDados(1) -radix hexadecimal} {/registrosegmento/saidaDados(0) -radix hexadecimal}} -subitemconfig {/registrosegmento/saidaDados(15) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(14) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(13) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(12) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(11) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(10) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(9) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(8) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(7) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(6) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(5) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(4) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(3) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(2) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(1) {-height 15 -radix hexadecimal} /registrosegmento/saidaDados(0) {-height 15 -radix hexadecimal}} /registrosegmento/saidaDados
add wave -noupdate -radix hexadecimal -childformat {{/registrosegmento/CS(15) -radix hexadecimal} {/registrosegmento/CS(14) -radix hexadecimal} {/registrosegmento/CS(13) -radix hexadecimal} {/registrosegmento/CS(12) -radix hexadecimal} {/registrosegmento/CS(11) -radix hexadecimal} {/registrosegmento/CS(10) -radix hexadecimal} {/registrosegmento/CS(9) -radix hexadecimal} {/registrosegmento/CS(8) -radix hexadecimal} {/registrosegmento/CS(7) -radix hexadecimal} {/registrosegmento/CS(6) -radix hexadecimal} {/registrosegmento/CS(5) -radix hexadecimal} {/registrosegmento/CS(4) -radix hexadecimal} {/registrosegmento/CS(3) -radix hexadecimal} {/registrosegmento/CS(2) -radix hexadecimal} {/registrosegmento/CS(1) -radix hexadecimal} {/registrosegmento/CS(0) -radix hexadecimal}} -subitemconfig {/registrosegmento/CS(15) {-height 15 -radix hexadecimal} /registrosegmento/CS(14) {-height 15 -radix hexadecimal} /registrosegmento/CS(13) {-height 15 -radix hexadecimal} /registrosegmento/CS(12) {-height 15 -radix hexadecimal} /registrosegmento/CS(11) {-height 15 -radix hexadecimal} /registrosegmento/CS(10) {-height 15 -radix hexadecimal} /registrosegmento/CS(9) {-height 15 -radix hexadecimal} /registrosegmento/CS(8) {-height 15 -radix hexadecimal} /registrosegmento/CS(7) {-height 15 -radix hexadecimal} /registrosegmento/CS(6) {-height 15 -radix hexadecimal} /registrosegmento/CS(5) {-height 15 -radix hexadecimal} /registrosegmento/CS(4) {-height 15 -radix hexadecimal} /registrosegmento/CS(3) {-height 15 -radix hexadecimal} /registrosegmento/CS(2) {-height 15 -radix hexadecimal} /registrosegmento/CS(1) {-height 15 -radix hexadecimal} /registrosegmento/CS(0) {-height 15 -radix hexadecimal}} /registrosegmento/CS
add wave -noupdate -radix hexadecimal -childformat {{/registrosegmento/DS(15) -radix hexadecimal} {/registrosegmento/DS(14) -radix hexadecimal} {/registrosegmento/DS(13) -radix hexadecimal} {/registrosegmento/DS(12) -radix hexadecimal} {/registrosegmento/DS(11) -radix hexadecimal} {/registrosegmento/DS(10) -radix hexadecimal} {/registrosegmento/DS(9) -radix hexadecimal} {/registrosegmento/DS(8) -radix hexadecimal} {/registrosegmento/DS(7) -radix hexadecimal} {/registrosegmento/DS(6) -radix hexadecimal} {/registrosegmento/DS(5) -radix hexadecimal} {/registrosegmento/DS(4) -radix hexadecimal} {/registrosegmento/DS(3) -radix hexadecimal} {/registrosegmento/DS(2) -radix hexadecimal} {/registrosegmento/DS(1) -radix hexadecimal} {/registrosegmento/DS(0) -radix hexadecimal}} -subitemconfig {/registrosegmento/DS(15) {-height 15 -radix hexadecimal} /registrosegmento/DS(14) {-height 15 -radix hexadecimal} /registrosegmento/DS(13) {-height 15 -radix hexadecimal} /registrosegmento/DS(12) {-height 15 -radix hexadecimal} /registrosegmento/DS(11) {-height 15 -radix hexadecimal} /registrosegmento/DS(10) {-height 15 -radix hexadecimal} /registrosegmento/DS(9) {-height 15 -radix hexadecimal} /registrosegmento/DS(8) {-height 15 -radix hexadecimal} /registrosegmento/DS(7) {-height 15 -radix hexadecimal} /registrosegmento/DS(6) {-height 15 -radix hexadecimal} /registrosegmento/DS(5) {-height 15 -radix hexadecimal} /registrosegmento/DS(4) {-height 15 -radix hexadecimal} /registrosegmento/DS(3) {-height 15 -radix hexadecimal} /registrosegmento/DS(2) {-height 15 -radix hexadecimal} /registrosegmento/DS(1) {-height 15 -radix hexadecimal} /registrosegmento/DS(0) {-height 15 -radix hexadecimal}} /registrosegmento/DS
add wave -noupdate -radix hexadecimal -childformat {{/registrosegmento/ES(15) -radix hexadecimal} {/registrosegmento/ES(14) -radix hexadecimal} {/registrosegmento/ES(13) -radix hexadecimal} {/registrosegmento/ES(12) -radix hexadecimal} {/registrosegmento/ES(11) -radix hexadecimal} {/registrosegmento/ES(10) -radix hexadecimal} {/registrosegmento/ES(9) -radix hexadecimal} {/registrosegmento/ES(8) -radix hexadecimal} {/registrosegmento/ES(7) -radix hexadecimal} {/registrosegmento/ES(6) -radix hexadecimal} {/registrosegmento/ES(5) -radix hexadecimal} {/registrosegmento/ES(4) -radix hexadecimal} {/registrosegmento/ES(3) -radix hexadecimal} {/registrosegmento/ES(2) -radix hexadecimal} {/registrosegmento/ES(1) -radix hexadecimal} {/registrosegmento/ES(0) -radix hexadecimal}} -subitemconfig {/registrosegmento/ES(15) {-height 15 -radix hexadecimal} /registrosegmento/ES(14) {-height 15 -radix hexadecimal} /registrosegmento/ES(13) {-height 15 -radix hexadecimal} /registrosegmento/ES(12) {-height 15 -radix hexadecimal} /registrosegmento/ES(11) {-height 15 -radix hexadecimal} /registrosegmento/ES(10) {-height 15 -radix hexadecimal} /registrosegmento/ES(9) {-height 15 -radix hexadecimal} /registrosegmento/ES(8) {-height 15 -radix hexadecimal} /registrosegmento/ES(7) {-height 15 -radix hexadecimal} /registrosegmento/ES(6) {-height 15 -radix hexadecimal} /registrosegmento/ES(5) {-height 15 -radix hexadecimal} /registrosegmento/ES(4) {-height 15 -radix hexadecimal} /registrosegmento/ES(3) {-height 15 -radix hexadecimal} /registrosegmento/ES(2) {-height 15 -radix hexadecimal} /registrosegmento/ES(1) {-height 15 -radix hexadecimal} /registrosegmento/ES(0) {-height 15 -radix hexadecimal}} /registrosegmento/ES
add wave -noupdate -radix hexadecimal -childformat {{/registrosegmento/IP(15) -radix hexadecimal} {/registrosegmento/IP(14) -radix hexadecimal} {/registrosegmento/IP(13) -radix hexadecimal} {/registrosegmento/IP(12) -radix hexadecimal} {/registrosegmento/IP(11) -radix hexadecimal} {/registrosegmento/IP(10) -radix hexadecimal} {/registrosegmento/IP(9) -radix hexadecimal} {/registrosegmento/IP(8) -radix hexadecimal} {/registrosegmento/IP(7) -radix hexadecimal} {/registrosegmento/IP(6) -radix hexadecimal} {/registrosegmento/IP(5) -radix hexadecimal} {/registrosegmento/IP(4) -radix hexadecimal} {/registrosegmento/IP(3) -radix hexadecimal} {/registrosegmento/IP(2) -radix hexadecimal} {/registrosegmento/IP(1) -radix hexadecimal} {/registrosegmento/IP(0) -radix hexadecimal}} -subitemconfig {/registrosegmento/IP(15) {-height 15 -radix hexadecimal} /registrosegmento/IP(14) {-height 15 -radix hexadecimal} /registrosegmento/IP(13) {-height 15 -radix hexadecimal} /registrosegmento/IP(12) {-height 15 -radix hexadecimal} /registrosegmento/IP(11) {-height 15 -radix hexadecimal} /registrosegmento/IP(10) {-height 15 -radix hexadecimal} /registrosegmento/IP(9) {-height 15 -radix hexadecimal} /registrosegmento/IP(8) {-height 15 -radix hexadecimal} /registrosegmento/IP(7) {-height 15 -radix hexadecimal} /registrosegmento/IP(6) {-height 15 -radix hexadecimal} /registrosegmento/IP(5) {-height 15 -radix hexadecimal} /registrosegmento/IP(4) {-height 15 -radix hexadecimal} /registrosegmento/IP(3) {-height 15 -radix hexadecimal} /registrosegmento/IP(2) {-height 15 -radix hexadecimal} /registrosegmento/IP(1) {-height 15 -radix hexadecimal} /registrosegmento/IP(0) {-height 15 -radix hexadecimal}} /registrosegmento/IP
add wave -noupdate -radix hexadecimal -childformat {{/registrosegmento/SS(15) -radix hexadecimal} {/registrosegmento/SS(14) -radix hexadecimal} {/registrosegmento/SS(13) -radix hexadecimal} {/registrosegmento/SS(12) -radix hexadecimal} {/registrosegmento/SS(11) -radix hexadecimal} {/registrosegmento/SS(10) -radix hexadecimal} {/registrosegmento/SS(9) -radix hexadecimal} {/registrosegmento/SS(8) -radix hexadecimal} {/registrosegmento/SS(7) -radix hexadecimal} {/registrosegmento/SS(6) -radix hexadecimal} {/registrosegmento/SS(5) -radix hexadecimal} {/registrosegmento/SS(4) -radix hexadecimal} {/registrosegmento/SS(3) -radix hexadecimal} {/registrosegmento/SS(2) -radix hexadecimal} {/registrosegmento/SS(1) -radix hexadecimal} {/registrosegmento/SS(0) -radix hexadecimal}} -subitemconfig {/registrosegmento/SS(15) {-height 15 -radix hexadecimal} /registrosegmento/SS(14) {-height 15 -radix hexadecimal} /registrosegmento/SS(13) {-height 15 -radix hexadecimal} /registrosegmento/SS(12) {-height 15 -radix hexadecimal} /registrosegmento/SS(11) {-height 15 -radix hexadecimal} /registrosegmento/SS(10) {-height 15 -radix hexadecimal} /registrosegmento/SS(9) {-height 15 -radix hexadecimal} /registrosegmento/SS(8) {-height 15 -radix hexadecimal} /registrosegmento/SS(7) {-height 15 -radix hexadecimal} /registrosegmento/SS(6) {-height 15 -radix hexadecimal} /registrosegmento/SS(5) {-height 15 -radix hexadecimal} /registrosegmento/SS(4) {-height 15 -radix hexadecimal} /registrosegmento/SS(3) {-height 15 -radix hexadecimal} /registrosegmento/SS(2) {-height 15 -radix hexadecimal} /registrosegmento/SS(1) {-height 15 -radix hexadecimal} /registrosegmento/SS(0) {-height 15 -radix hexadecimal}} /registrosegmento/SS
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {388302 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 236
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1050 ns}
view wave 
wave clipboard store
wave create -driver freeze -pattern clock -initialvalue 0 -period 100ps -dutycycle 50 -starttime 0ns -endtime 1000ns sim:/registrosegmento/clock 
wave modify -driver freeze -pattern clock -initialvalue 0 -period 100ns -dutycycle 50 -starttime 0ns -endtime 1000ns Edit:/registrosegmento/clock 
wave create -driver freeze -pattern constant -value 1 -starttime 0ns -endtime 1000ns sim:/registrosegmento/habilita 
wave create -driver freeze -pattern constant -value 0000000011111111 -range 15 0 -starttime 0ps -endtime 1000ps sim:/registrosegmento/entradaDados 
WaveExpandAll -1
wave modify -driver freeze -pattern random -initialvalue 0000000000000000 -period 50ns -random_type Uniform -seed 5 -range 15 0 -starttime 0ns -endtime 1000ns Edit:/registrosegmento/entradaDados 
wave modify -driver freeze -pattern random -initialvalue 0000000000000000 -period 100ns -random_type Uniform -seed 5 -range 15 0 -starttime 0ns -endtime 1000ns Edit:/registrosegmento/entradaDados 
wave create -driver freeze -pattern constant -value 0 -starttime 0ns -endtime 1000ns sim:/registrosegmento/leitura_Escrita 
wave create -driver freeze -pattern constant -value 1 -starttime 0ns -endtime 1000ns sim:/registrosegmento/reset 
wave create -driver freeze -pattern constant -value 000 -range 2 0 -starttime 0ns -endtime 1000ns sim:/registrosegmento/seletor 
WaveExpandAll -1
wave create -driver freeze -pattern constant -value 0 -starttime 0ns -endtime 1000ns sim:/registrosegmento/soma_IP 
wave modify -driver freeze -pattern clock -initialvalue 0 -period 50ns -dutycycle 50 -starttime 0ns -endtime 1000ns Edit:/registrosegmento/clock 
wave edit change_value -start 0ps -end 248632ps -value 0 Edit:/registrosegmento/reset 
wave edit change_value -start 146604ps -end 277358ps -value 001 Edit:/registrosegmento/seletor 
wave edit change_value -start 277358ps -end 424953ps -value 010 Edit:/registrosegmento/seletor 
wave edit change_value -start 425943ps -end 541840ps -value 011 Edit:/registrosegmento/seletor 
wave edit change_value -start 541840ps -end 630000ps -value 100 Edit:/registrosegmento/seletor 
wave edit change_value -start 714198ps -end 782547ps -value 001 Edit:/registrosegmento/seletor 
wave edit change_value -start 782547ps -end 850896ps -value 010 Edit:/registrosegmento/seletor 
wave edit change_value -start 848915ps -end 995519ps -value 100 Edit:/registrosegmento/seletor 
wave edit invert -start 276368ps -end 487358ps Edit:/registrosegmento/soma_IP 
wave edit invert -start 599292ps -end 1000000ps Edit:/registrosegmento/leitura_Escrita 
wave edit invert -start 289245ps -end 619104ps Edit:/registrosegmento/habilita 
wave edit change_value -start 388302ps -end 630000ps -value 1 Edit:/registrosegmento/habilita 
WaveCollapseAll -1
wave clipboard restore
